config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id', to: 'tasks#show', as: 'task'


  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :detail)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :detail %>
  <%= f.text_field :detail %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<% @tasks.each do |task| %>
  <h2><%= task.title%></h2>
  <p><%= task.detail %></p>
  <p><%= link_to "Show", task_path(task) %></p>
  <p><%= link_to "Update", edit_task_path(task) %></p>
  <p><%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
<% end %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<%= render 'form' %>


<!-- <form action="/tasks" method="post">
  <label for="title">Titile: </label>
  <input type="text" name="task[title]" id="title">

  <label for="detail">Datail: </label>
  <input type="text" name="task[detail]" id="detail">

  <input type="submit">
</form> -->

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<h2><%= @task.title %></h2>
<p><%= @task.detail %></p>